services:
  - type: web
    name: django-api-react
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn DjangoAPI.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com 